work_dir: ./work_dir/ntu120/XSet/bone_global2d_0510

# feeder
feeder: dataset.feeder_xy.Feeder
train_feeder_args: 
  xy_path: /data1/liujinfu/global_xy
  sample_txt_path: /data-home/liujinfu/GCN/dataset/NTU120_XSet_train.txt
  label_txt_path: /data-home/liujinfu/GCN/dataset/NTU120_XSet_train_label.txt
  bone: True
  vel: False

test_feeder_args:
  xy_path: /data1/liujinfu/global_xy
  sample_txt_path: /data-home/liujinfu/GCN/dataset/NTU120_XSet_val.txt
  label_txt_path: /data-home/liujinfu/GCN/dataset/NTU120_XSet_val_label.txt
  bone: True
  vel: False

# model
model: model.ctrgcn_global_local.Model
model_args:
  num_class: 120
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True
