DATA:
    Data_path: /data/liujinfu/dataset/Toyota-Smarthome/person_224
    TRAIN_FILE: /data/liujinfu/dataset/Toyota-Smarthome/train_CV2.txt
    VAL_FILE: /data/liujinfu/dataset/Toyota-Smarthome/test_CV2.txt
    NUM_FRAMES: 8
    NUM_CLASSES: 19
    LABEL_LIST: /data/liujinfu/TPAMI-24/TPAMI-24/HPNet/configs/Smarthome/CV_label_name.txt
    BENCHMARK: Smarthome-CS
    ske_feature_data_path: /data/liujinfu/dataset/Toyota-Smarthome/pooling
    ske_train_sample_txt_path: /data/liujinfu/dataset/Toyota-Smarthome/train_CV2.txt
    ske_val_sample_txt_path: /data/liujinfu/dataset/Toyota-Smarthome/test_CV2.txt
    bone: True
    vel: True
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 # 16 4
    ACCUMULATION_STEPS: 4
    NUM_WORKERS: 4
    EPOCHS: 30
TEST:
    BATCH_SIZE: 4