work_dir: ./work_dir/ntu60/NTU60_XView/bonemotion_pooling_0509

# feeder
feeder: dataset.feeder_4m.Feeder
train_feeder_args: 
  feature_data_path: /data1/liujinfu/joint
  sample_txt_path: /data-home/liujinfu/GCN/dataset/NTU60_XView_train.txt
  label_txt_path: /data-home/liujinfu/GCN/dataset/NTU60_XView_train_label.txt
  bone: True
  vel: True

test_feeder_args:
  feature_data_path: /data1/liujinfu/joint
  sample_txt_path: /data-home/liujinfu/GCN/dataset/NTU60_XView_val.txt
  label_txt_path: /data-home/liujinfu/GCN/dataset/NTU60_XView_val_label.txt
  bone: True
  vel: True

# model
model: model.ctrgcn_feature2.Model
model_args:
  num_class: 60
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True
