work_dir: ./work_dir/UAV/CSv2_jointmotion_pooling_0202

# feeder
feeder: dataset.feeder_uav.Feeder
train_feeder_args: 
  feature_data_path: /data/liujinfu/dataset/UAV/pooling
  sample_txt_path: /data/liujinfu/dataset/UAV/Process_Pose/new_CS_train_V2.txt
  bone: False
  vel: True

test_feeder_args:
  feature_data_path: /data/liujinfu/dataset/UAV/pooling
  sample_txt_path: /data/liujinfu/dataset/UAV/Process_Pose/new_CS_test_V2.txt
  bone: False
  vel: True

# model
model: model.ctrgcn_feature2.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

# optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True
